'use strict';
// Real Git/Node/reference generation probes. No injected model verdict is PASS.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const D=require('../../scripts/kodjo/qualify-vnext-figma-real-path'),C=require('../../scripts/kodjo/lib/vnext-disposable-functional-contract'),Chain=require('../../scripts/kodjo/lib/vnext-live-chain'),Recipe=require('../../scripts/kodjo/lib/vnext-figma-recipe'),Adapter=require('../../scripts/kodjo/lib/vnext-legacy-queue-adapter'),Review=require('../../scripts/kodjo/lib/vnext-figma-implementation-review'),V=require('../../scripts/kodjo/lib/vnext-contract'),Fixture=require('./helpers/vnext-figma-fixture');
const reference="const {Existing}=require('../../shared/ui/Existing');let selected=false;module.exports={Existing,toggle(){return selected=!selected;}};\n";
async function prepare(t){
 const f=Fixture.fixture({launchMode:true,documentContent:D.DOCUMENT,documentaryStates:D.DOCUMENTARY_STATES,transformPacket:p=>D.scopedPacket(p,p.documents[0])});t.after(f.cleanup);
 const out=fs.mkdtempSync(path.join(os.tmpdir(),'vnext-coherence-'));t.after(()=>fs.rmSync(out,{recursive:true,force:true}));
 const scope={slice_id:f.recipe.planningInput.slice_id,launch_id:'REFERENCE-NO-MODEL',file_key:f.snapshot.file_key,frames:f.snapshot.frames,documents:f.snapshot.documents};
 const produced=await Chain.launchAndProduce(scope,{cwd:f.cwd,capture:s=>D.capture(f.snapshot,s),reconcile:(raw,documents)=>({...raw,documents,states:f.snapshot.states,decisions:f.snapshot.decisions,conflicts:[]}),persist:()=>({revision:f.head,path:f.packetPath,content:Chain.readGit(f.cwd,f.head,f.packetPath)}),buildRecipe:c=>Recipe.build(f.cwd,c,{applicationPath:C.SCREEN,testPath:C.TEST,componentPath:C.KEEP,componentBinding:D.BINDING,qualificationContract:D.QUALIFICATION_CONTRACT,scenarioPropertyType:'STATE',observationIntent:'Reference probe: functional only; no visual gate.',issueId:'github_issue:MyUncried/Application-Routine#269',intent:'Reference fixture implements documentary toggle transitions; MODIFY existing Screen and preserve Existing.',executionContext:{mode:'LOCAL',writer_id:'CLAUDE:figma-disposable'}})});
 Chain.verifyProduced(produced,f.cwd);const a=produced.artifacts,plan=Adapter.renderCompatibilityPlan({application_head:a.planningEnvelope.application_head,plan_contract_hash:a.planContract.contract_hash},a.planContract,a.uiAtomicityContract,a.requirementRegistry,a.candidateManifest);
 f.write(C.SCREEN,reference);
 const delivered=`const assert=require('node:assert/strict'),cp=require('node:child_process');\nconst transition=JSON.parse(cp.execFileSync(process.execPath,['-e',${JSON.stringify('process.stdout.write(JSON.stringify(('+C.transitions.toString()+')(require("node:path").resolve('+JSON.stringify(C.SCREEN)+'))));')}],{encoding:'utf8'}));assert.deepEqual(transition.returned_values,[true,false]);\ncp.execFileSync(process.execPath,['-e',${JSON.stringify('('+C.preservation.toString()+')(require("node:path").resolve('+JSON.stringify(C.SCREEN)+'),require("node:path").resolve('+JSON.stringify(C.KEEP)+'));')}]);\n`;
 f.write(C.TEST,delivered);const keepHash=V.sha256(fs.readFileSync(path.join(f.cwd,C.KEEP)));return {f,out,plan,produced,keepHash};
}
test('generated plan, real reference delivery, independent probes and reviewer-accessible dossier agree',async t=>{
 const {f,out,plan,produced,keepHash}=await prepare(t);assert.ok(plan.includes(C.EXPECTED));assert.match(plan,/require the shared module again/);assert.match(plan,/SAME Screen module instance in ONE fresh child/);
 assert.deepEqual(produced.artifacts.impactGraph.impacts.filter(i=>i.change_kind==='MODIFY').map(i=>i.candidate_id).sort(),produced.artifacts.candidateManifest.candidates.filter(c=>[C.SCREEN,C.TEST].includes(c.path)).map(c=>c.candidate_id).sort());
 assert.equal(produced.artifacts.planContract.plan_items.flatMap(p=>p.proof_obligations).some(p=>p.proof_type==='VISUAL_COMPARE'),false);
 const receipt=D.runDeliveredTests(f,keepHash,path.join(out,'gate.json'));f.git('add',C.SCREEN,C.TEST);f.git('commit','-m','REFERENCE deterministic delivery; no model');
 const options=D.compare(f,f.snapshot,plan,path.join(out,'review'),receipt),dossier=Review.prepare(plan,options);
 const artifact=JSON.parse(fs.readFileSync(path.join(out,'review','execution.json')));
 assert.deepEqual(artifact.returned_values,[true,false]);assert.equal(artifact.module_instances,1);assert.deepEqual(artifact.call_order,['toggle-off-on','toggle-on-off']);
 assert.deepEqual(artifact.node_test_receipt.preservation_probe,{status:'PASS',normal_identity:true,sentinel_identity:true,independent_child_process:true});
 assert.equal(dossier.observed_files.length,1);assert.equal(dossier.observed_files[0].file,path.join(out,'review','execution.json'));assert.equal(artifact.node_test_receipt.source_sha256[C.KEEP],keepHash);
 assert.equal(dossier.measurements.length,0);assert.equal(dossier.scenario_ids.length,2);
});
for(const [name,body,diagnostic] of [
 ['constant shared value',"let selected=false;module.exports={Existing:true,toggle:()=>selected=!selected};",/PROVENANCE_FAILED/],
 ['missing shared export',"let selected=false;module.exports={toggle:()=>selected=!selected};",/PRESERVATION_FAILED/],
 ['replaced shared module',reference,/WRITE_SCOPE_REFUSED|PRESERVATION_FAILED/]
])test('independent preservation refuses '+name+' even if delivered test passes',async t=>{const {f,out,keepHash}=await prepare(t);f.write(C.SCREEN,body);f.write(C.TEST,'// Deliberately empty passing test: cannot establish preservation.\n');if(name==='replaced shared module')f.write(C.KEEP,'module.exports={Existing:false};\n');assert.throws(()=>D.runDeliveredTests(f,keepHash,path.join(out,'failed-gate.json')),diagnostic);assert.equal(JSON.parse(fs.readFileSync(path.join(out,'failed-gate.json'))).status,'FAIL');});
for(const [name,body] of [
 ['always true',"const {Existing}=require('../../shared/ui/Existing');module.exports={Existing,toggle:()=>true};"],
 ['wrong initial state',"const {Existing}=require('../../shared/ui/Existing');let selected=true;module.exports={Existing,toggle:()=>selected=!selected};"],
 ['injected functional fault',reference+D.NEGATIVE_FUNCTIONAL_FAULT]
])test('real generated dossier refuses '+name+' despite a passing delivered Node test',async t=>{const {f,out,plan,keepHash}=await prepare(t);f.write(C.SCREEN,body);f.write(C.TEST,'// Intentionally vacuous test; independent observer must refuse.\n');const receipt=D.runDeliveredTests(f,keepHash);assert.equal(receipt.status,'PASS');assert.throws(()=>D.compare(f,f.snapshot,plan,path.join(out,'negative'),receipt),/SCENARIO_NOT_PASSED/);});
test('receipt corruption and changed shared source cannot reach the reviewer',async t=>{const {f,out,keepHash}=await prepare(t),receipt=D.runDeliveredTests(f,keepHash);const bad=structuredClone(receipt);delete bad.preservation_probe;assert.throws(()=>D.observe(f,f.snapshot,path.join(out,'unused'),bad),/PRESERVATION_RECEIPT_INVALID/);f.write(C.KEEP,'module.exports={Existing:true};\n// drift\n');assert.throws(()=>D.observe(f,f.snapshot,path.join(out,'unused'),receipt),/RECEIPT_SOURCE_DRIFT/);});
test('functional fault is rejected and exact causal correction restores the same generated dossier',async t=>{const {f,out,plan,keepHash}=await prepare(t),original=fs.readFileSync(path.join(f.cwd,C.SCREEN));const receipt=D.runDeliveredTests(f,keepHash);D.compare(f,f.snapshot,plan,path.join(out,'before'),receipt);f.write(C.SCREEN,original.toString()+D.NEGATIVE_FUNCTIONAL_FAULT);assert.throws(()=>D.compare(f,f.snapshot,plan,path.join(out,'negative')),/SCENARIO_NOT_PASSED/);f.write(C.SCREEN,original.toString());const corrected=D.runDeliveredTests(f,keepHash);const options=D.compare(f,f.snapshot,plan,path.join(out,'corrected'),corrected);assert.equal(Review.prepare(plan,options).scenario_ids.length,2);assert.deepEqual(fs.readFileSync(path.join(f.cwd,C.SCREEN)),original);});
