'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../../scripts/kodjo/signal-vnext-cycle-continuation');
function fixture(){
 const c={repository:'MyUncried/Application-Routine',campaign_id:'628b3349-88b4-4bf1-be6b-50bc09e7d245',slice_id:'VNEXT-12-QUALIF',cycle_id:'de2b9683-7c6d-4ba3-9dc4-4664dbaee0c3',request_id:'db5ed26b-e1f7-4e0c-a417-1ee1f44748a4',revision_limit:1,pre1_in_scope:false,final_audit_authorized:false,human_review_performed:false,auto_continue:true,stage:'EXECUTE_INITIAL',generation:80};
 const head='a'.repeat(40),next='b'.repeat(40),writes=[];let current=head,message='';
 const api=(p,m='GET',d)=>{if(m!=='GET'){writes.push({p,m,d});if(p.endsWith('/blobs'))return{sha:'c'.repeat(40)};if(p.endsWith('/trees'))return{sha:'d'.repeat(40)};if(p.endsWith('/commits')){message=d.message;return{sha:next};}if(m==='PATCH'){current=d.sha;return{object:{sha:current}};}}if(p.endsWith('/pulls/269'))return{state:'open',head:{repo:{full_name:c.repository},ref:'protocol/vnext-proof-stability-20260930'}};if(p.includes('/refs/heads/'))return{object:{sha:current}};return{tree:{sha:'e'.repeat(40)},message};};
 return{c,writes,opts:{api,head,runId:10,attempt:1,kind:'OPERATIONAL',results:{'execute-initial':{result:'success'}}},move:()=>{current='f'.repeat(40);}};
}
test('completion signal writes one isolated evidence path and authorizes no implementation',()=>{const x=fixture();assert.equal(C.signal(x.c,x.opts).status,'SIGNAL_PUBLISHED');const tree=x.writes.find(w=>w.p.endsWith('/trees'));assert.equal(tree.d.tree.length,1);assert.match(tree.d.tree[0].path,/continuation-signal.json$/);const record=JSON.parse(x.writes.find(w=>w.p.endsWith('/blobs')).d.content);assert.equal(record.implementation_authorized,false);assert.equal(record.business_write,false);assert.equal(x.writes.at(-1).d.force,false);});
test('same completed request reuses its signal without a second commit',()=>{const x=fixture();C.signal(x.c,x.opts);x.writes.length=0;assert.equal(C.signal(x.c,x.opts).status,'REUSED_EXISTING_SIGNAL');assert.equal(x.writes.length,0);});
test('late completion leaves a newer controller unchanged',()=>{const x=fixture();x.move();assert.equal(C.signal(x.c,x.opts).status,'SKIPPED_CONTROLLER_MOVED');assert.equal(x.writes.length,0);});
test('unqualified control completion cannot signal readiness',()=>{const x=fixture();x.opts.kind='QUALIFICATION';assert.throws(()=>C.signal(x.c,x.opts),/NOT_READY/);assert.equal(x.writes.length,0);x.opts.results={qualification:{result:'success'}};assert.equal(C.signal(x.c,x.opts).status,'SIGNAL_PUBLISHED');});
test('foreign campaign and terminal operational request cannot write',()=>{for(const mutate of [c=>c.campaign_id='other',c=>c.auto_continue=false,c=>c.stage='TARGETED_RESULT_RECORDED']){const x=fixture();mutate(x.c);assert.throws(()=>C.signal(x.c,x.opts),/REFUSED/);assert.equal(x.writes.length,0);}});
test('materialization replaces historical request identity and retains exact prepared bootstrap',()=>{const x=fixture();Object.assign(x.c,{execution_request_id:x.c.request_id,execution_created_at:'2026-10-07T10:40:00Z'});const t={slice_bootstrap_file:'bootstrap',slice_bootstrap_sha256:'a'.repeat(64),plan_path:'plan',review_path:'review',prompt_file:'mission',request_id:'OLD_CONSUMED',gate_ref:'OLD_GATE'};const r=C.materializeTransport(t,x.c);assert.equal(r.request_id,x.c.request_id);assert.equal(r.slice_bootstrap_sha256,t.slice_bootstrap_sha256);assert.equal(r.gate_ref,undefined);assert.throws(()=>C.materializeTransport(t,{...x.c,execution_created_at:'invalid'}),/INVALID/);});

test('workflow continuation depends on existing jobs and follows bounded stages',()=>{const fs=require('fs');const w=fs.readFileSync('.github/workflows/kodjo-vnext12-disposable.yml','utf8');const jobs=new Set([...w.matchAll(/^  ([a-z][a-z0-9-]+):$/gm)].map(m=>m[1]));const wake=w.split('\n  wake-orchestrator:')[1];const needs=/needs: \[([^\]]+)\]/.exec(wake)[1].split(',').map(x=>x.trim());for(const j of needs)assert.ok(jobs.has(j),'missing job '+j);assert.match(wake,/auto_continue == 'true'/);assert.match(wake,/TARGETED_RESULT_RECORDED/);assert.match(wake,/VNEXT_RUN_KIND: OPERATIONAL/);assert.match(w,/stage == 'CERTIFY_HISTORICAL'/);assert.match(w,/stage == 'CERTIFY_HISTORICAL' \|\| needs\.figma-initial\.result == 'success'/);const q=fs.readFileSync('.github/workflows/kodjo-vnext-proof-stability.yml','utf8').split('\n  wake-orchestrator:')[1];assert.match(q,/needs: qualification/);assert.match(q,/qualification.result == 'success'/);assert.match(q,/qualification\/vnext-full-cycle-/);});
