'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../../scripts/kodjo/lib/vnext-github-closure'),V=require('../../scripts/kodjo/lib/vnext-contract');
function fixture(){
 const c={stage:'FINALIZE_DELIVERY',repository:'MyUncried/Application-Routine',slice_id:'VNEXT-12-QUALIF',campaign_id:'628b3349-88b4-4bf1-be6b-50bc09e7d245',closure_scope:'GITHUB_CERTIFICATION_DELIVERY',pre1_in_scope:false,final_audit_authorized:false,revision_limit:1,issue_number:900,delivery_pr_number:901,delivery_branch:'certification/vnext/628b3349-88b4-4bf1-be6b-50bc09e7d245',delivery_head:'a'.repeat(40),finalization_manifest:'docs/finalization.json'};
 const issue={state:'open',html_url:`https://github.com/${c.repository}/issues/900`,body:C.binding(c)+'Fixture only, no real GitHub writes.'};c.issue_body_sha256=V.sha256(issue.body);
 const pr={state:'open',merged:false,html_url:`https://github.com/${c.repository}/pull/901`,head:{sha:c.delivery_head,ref:c.delivery_branch,repo:{full_name:c.repository}},base:{ref:'protocol/vnext-proof-stability-20260930',repo:{full_name:c.repository}}};
 const f=V.sealContract({schema_version:'kodjo.vnext.finalization.v1',final_status:'READY_TO_CLOSE',repository:c.repository,issue_number:c.issue_number,slice_id:c.slice_id,head:c.delivery_head,review_comment_id:'902',original_decision:{comment_id:'903',body:'Functional only; pending device'},reservations:['pending device'],pending_proofs:[{status:'PENDING_DEVICE'}],proof_resolutions:[{resolution:'USER_WAIVER'}],not_executed_proofs:[],acceptance_scope:'FUNCTIONAL_ACCEPTANCE_WITH_RESERVES',visual_compliance_attested:false,accessibility_compliance_attested:false});
 const comments=[],writes=[];const github={issue:()=>structuredClone(issue),pull:()=>structuredClone(pr),comments:()=>structuredClone(comments),comment:(r,n,body)=>{const x={id:1000+comments.length,body,user:{login:'github-actions[bot]'}};comments.push(x);writes.push('comment');return x;},closeIssue:()=>{writes.push('close');issue.state='closed';issue.state_reason='completed';}};
 return{c,f,issue,pr,comments,writes,github};
}
test('GitHub consumer preserves pending evidence and records only certification closure',()=>{const x=fixture(),r=C.close(x.c,x.f,x.github);assert.equal(r.github_issue_closed,true);assert.equal(r.application_published,false);assert.equal(r.pending_proofs[0].status,'PENDING_DEVICE');assert.equal(r.visual_compliance_attested,false);assert.deepEqual(x.writes,['comment','close','comment']);});
test('completed closure repeats without any write',()=>{const x=fixture(),first=C.close(x.c,x.f,x.github);x.writes.length=0;assert.deepEqual(C.close(x.c,x.f,x.github),first);assert.deepEqual(x.writes,[]);});
for(const boundary of ['comment','close'])test('response lost after '+boundary+' resumes from observed remote state',()=>{const x=fixture(),original=x.github[boundary==='close'?'closeIssue':'comment'];let lost=true;x.github[boundary==='close'?'closeIssue':'comment']=(...args)=>{const r=original(...args);if(lost){lost=false;throw Error('response lost');}return r;};assert.throws(()=>C.close(x.c,x.f,x.github),/response lost/);C.close(x.c,x.f,x.github);assert.equal(x.comments.length,2);assert.equal(x.writes.filter(v=>v==='close').length,1);});
test('conflicting or duplicate publication is refused',()=>{for(const duplicate of [false,true]){const x=fixture(),p=C.prepare(x.c,x.f);x.comments.push({id:1,body:p.finalBody});x.comments.push({id:2,body:duplicate?p.finalBody:p.finalBody+'drift'});assert.throws(()=>C.close(x.c,x.f,x.github),/RECORD_CONFLICT/);assert.deepEqual(x.writes,[]);}});
test('unrelated issue, protocol PR, changed head or foreign branch refuses before writing',()=>{for(const change of [x=>x.issue.body+='changed',x=>x.pr.head.sha='b'.repeat(40),x=>x.pr.head.ref='main',x=>x.c.issue_number=269,x=>x.issue.pull_request={}]){const x=fixture();change(x);assert.throws(()=>C.close(x.c,x.f,x.github),/REFUSED|DRIFT/);assert.deepEqual(x.writes,[]);}});
test('head moved after final output refuses closure',()=>{const x=fixture(),write=x.github.comment;x.github.comment=(...args)=>{const r=write(...args);x.pr.head.sha='b'.repeat(40);return r;};assert.throws(()=>C.close(x.c,x.f,x.github),/TARGET_DRIFT/);assert.equal(x.issue.state,'open');assert.deepEqual(x.writes,['comment']);});
test('unrelated closed issue or premature closure marker is refused',()=>{const x=fixture();x.issue.state='closed';assert.throws(()=>C.close(x.c,x.f,x.github),/STATE_CONFLICT/);x.issue.state='open';x.comments.push({id:1,body:C.prepare(x.c,x.f).closedBody,user:{login:'github-actions[bot]'}});assert.throws(()=>C.close(x.c,x.f,x.github),/STATE_CONFLICT/);});
test('unapproved finalization, another delivery and tampered envelope refuse',()=>{for(const change of [f=>f.final_status='FAIL',f=>f.head='b'.repeat(40),f=>f.visual_compliance_attested=true]){const x=fixture(),f={...x.f};delete f.contract_hash;change(f);assert.throws(()=>C.close(x.c,V.sealContract(f),x.github),/FINALIZATION_BINDING/);assert.deepEqual(x.writes,[]);}const x=fixture();const altered=structuredClone(x.f);altered.reservations=[];assert.throws(()=>C.close(x.c,altered,x.github),/FINALIZATION_HASH/);});
test('workflow routes closure exclusively and preserves terminal request',()=>{const fs=require('fs'),source=fs.readFileSync('.github/workflows/kodjo-vnext12-disposable.yml','utf8');assert.match(source,/group: kodjo-vnext12-disposable/);assert.match(source,/cancel-in-progress: false/);assert.match(source,/stage == 'FINALIZE_DELIVERY'/);assert.match(source,/issues: write/);assert.match(source,/TARGETED_RESULT_RECORDED/);});
test('a copied closure record from another actor is refused',()=>{const x=fixture();x.comments.push({id:1,body:C.prepare(x.c,x.f).finalBody,user:{login:'someone-else'}});assert.throws(()=>C.close(x.c,x.f,x.github),/RECORD_CONFLICT/);assert.deepEqual(x.writes,[]);});
test('non-UI finalization covers exact required proofs and delivered targets',()=>{
 const fs=require('fs'),os=require('os'),path=require('path'),{execFileSync}=require('child_process'),F=require('../../scripts/kodjo/lib/vnext-finalization');
 const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'vnext-nonui-final-'));
 const git=(...args)=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
 try{git('init','-q');git('config','user.name','Fixture');git('config','user.email','fixture@example.invalid');fs.writeFileSync(path.join(cwd,'keep.js'),'keep');git('add','.');git('commit','-qm','baseline');const baselineHead=git('rev-parse','HEAD');fs.writeFileSync(path.join(cwd,'delivered.js'),'value=2');git('add','.');git('commit','-qm','delivery');const head=git('rev-parse','HEAD');
 const requirement={requirement_id:'R-1',change_targets:['delivered.js'],proof_required:['FUNCTIONAL_TEST']};
 const args={cwd,matrix:{criteria:[]},review:{verdict:'APPROVE',criteria:[],non_ui_plan_assessment:{status:'CONFORME',requirements:[{requirement_id:'R-1',status:'CONFORME',proof_results:[{proof_type:'FUNCTIONAL_TEST',status:'PASS',evidence:'fixture executed assertion'}]}]}},baselineHead,incrementHead:baselineHead,head,approvedHead:head,repository:'MyUncried/Application-Routine',issue:900,sliceId:'VNEXT-12-QUALIF',reviewId:'901',nonUiRequirements:[requirement],checks:{jest:'PASS',typescript:'PASS',lint:'PASS',head:'PASS',clean:'PASS'}};
 assert.equal(F.finalize(args).delivery_coverage.current_files[0].path,'delivered.js');
 assert.throws(()=>F.finalize({...args,nonUiRequirements:[{...requirement,change_targets:['missing.js']}]}),/TARGET_ABSENT/);
 assert.throws(()=>F.finalize({...args,nonUiRequirements:[{...requirement,requirement_id:'R-2'}]}),/NON_UI_COVERAGE_INVALID/);
 assert.throws(()=>F.finalize({...args,nonUiRequirements:[{...requirement,proof_required:['FUNCTIONAL_TEST','STATIC_ANALYSIS']}]}),/NON_UI_PROOF_COVERAGE_INVALID/);
 }finally{fs.rmSync(cwd,{recursive:true,force:true});}
});
