'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const D=require('../../scripts/kodjo/qualify-vnext-figma-real-path'),Q=require('../../scripts/kodjo/lib/vnext-github-qualification'),F=require('./helpers/vnext-figma-fixture');
const campaign='628b3349-88b4-4bf1-be6b-50bc09e7d245';
function config(head){return {stage:'FIGMA_INITIAL',campaign_id:campaign,slice_id:'VNEXT-12-QUALIF',revision_limit:1,pre1_in_scope:false,final_audit_authorized:false,authorization_basis:'CODEX_USER_DELEGATION_TASK2_DISPOSABLE_ONLY',human_review_performed:false,approved_protocol_head:head,qualification_run_id:7,request_id:'7849e723-403b-4890-b159-b7993b423aa7'};}
function fixture(t){const f=F.fixture();t.after(f.cleanup);const out=fs.mkdtempSync(path.join(os.tmpdir(),'vnext-real-test-'));t.after(()=>fs.rmSync(out,{recursive:true,force:true}));return {f,out};}
function read(head){return endpoint=>endpoint.endsWith('/pulls/269')?{head:{sha:head}}:endpoint.endsWith('/actions/runs/7')?{id:7,repository:{full_name:'MyUncried/Application-Routine'},head_sha:head,path:Q.WORKFLOW,event:'pull_request',status:'completed',conclusion:'success',run_attempt:1}:{jobs:Q.JOBS.map((name,i)=>({id:i+1,name,head_sha:head,status:'completed',conclusion:'success'}))};}
function env(head){return {GITHUB_ACTIONS:'true',GITHUB_REPOSITORY:'MyUncried/Application-Routine',GITHUB_RUN_ID:'21',GITHUB_RUN_ATTEMPT:'1',EXPECTED_RUNNER_NAME:'TEST-RUNNER',RUNNER_NAME:'TEST-RUNNER',KODJO_FIGMA_CONTROLLER_HEAD:head};}
test('real Figma driver requires the same campaign, bounded scope and explicit technical delegation',()=>{const c=config('a'.repeat(40));D.validateConfig(c);for(const change of [{stage:'FIGMA_CLOSURE'},{campaign_id:'different'},{pre1_in_scope:true},{revision_limit:2},{human_review_performed:true},{authorization_basis:'implicit'},{qualification_run_id:null},{request_id:'invalid'}])assert.throws(()=>D.validateConfig({...c,...change}),/CONFIG_REFUSED|REQUEST_REQUIRED/);});
test('qualification and current PR head precede an exclusive persistent claim; duplicate calls cannot reclaim it',t=>{const {f,out}=fixture(t),c=config(f.head),options={cwd:f.cwd,env:env(f.head),read:read(f.head),stateRoot:out};assert.throws(()=>D.claimRequest(c,{...options,env:{...options.env,GITHUB_RUN_ATTEMPT:'2'}}),/CONTEXT_REFUSED/);assert.throws(()=>D.claimRequest(c,{...options,read:read('b'.repeat(40))}),/REMOTE_HEAD_MOVED/);const first=D.claimRequest(c,options);assert.equal(first.claim.qualifications.approved.status,'VERIFIED');assert.ok(fs.existsSync(path.join(first.directory,'started.json')));assert.throws(()=>D.claimRequest(c,options),/EEXIST/);});
test('delivery bundle and uncommitted working delta remain recoverable after fixture cleanup',t=>{const {f,out}=fixture(t);f.write('src/features/example/Screen.js',"module.exports={Existing:true,qualification:'TEST uncommitted delta'};\n");const p=D.preserveFixture(f,out);assert.equal(p.head,f.head);assert.match(fs.readFileSync(path.join(out,'working-delta.patch'),'utf8'),/TEST uncommitted delta/);assert.ok(p.bundle_sha256);f.cleanup();const restored=path.join(out,'restored');require('node:child_process').execFileSync('git',['-c','core.autocrlf=false','clone','--quiet',path.join(out,'delivery.bundle'),restored]);assert.equal(require('node:child_process').execFileSync('git',['rev-parse','HEAD'],{cwd:restored,encoding:'utf8'}).trim(),p.head);assert.match(fs.readFileSync(path.join(out,'delivered-screen.js'),'utf8'),/TEST uncommitted delta/);});
